### ISSUE TITLE
Error Opening Season Folders

### ISSUE THREAD

**Issue by breaksrmine** [fayer3/plugin.video.joyn_app#4]
Example: (Pro7) Late Night Berlin & Duell um die Welt, not possible to open Season folders. 

Platform: OSMC (Vero4k+)
Joyn_app v0.2.6

`2019-09-30 11:21:07.736 T:2741887712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: timestamp out of range for platform time_t
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.joyn_app/main.py", line 14, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.joyn_app/resources/lib/plugin.py", line 1063, in run
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.joyn_app/resources/lib/plugin.py", line 540, in show_season
                                                endDATES = datetime.fromtimestamp(int(item['visibilities'][0]['endsAt']))
                                            ValueError: timestamp out of range for platform time_t
                                            -->End of Python script error report<--
2019-09-30 11:21:07.737 T:2741887712   DEBUG: onExecutionDone(371, /home/osmc/.kodi/addons/plugin.video.joyn_app/main.py)
2019-09-30 11:21:07.740 T:4064436224   DEBUG: ------ Window Init (DialogNotification.xml) ------
2019-09-30 11:21:08.120 T:2741887712    INFO: Python interpreter stopped
2019-09-30 11:21:08.120 T:2741887712   DEBUG: Thread LanguageInvoker 2741887712 terminating
2019-09-30 11:21:08.139 T:2674709216   ERROR: GetDirectory - Error getting plugin://plugin.video.joyn_app/season/id=c_pl2vow79b02
2019-09-30 11:21:08.163 T:2674709216   DEBUG: Thread waiting 2674709216 terminating
2019-09-30 11:21:08.171 T:4064436224   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-09-30 11:21:08.173 T:4064436224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.joyn_app/season/id=c_pl2vow79b02) failed `

**Comment by fayer3** [comment]
can you test if it works with the attached version
[plugin.video.joyn_app-0.2.7.zip](https://github.com/fayer3/plugin.video.joyn_app/files/3672067/plugin.video.joyn_app-0.2.7.zip)

**Comment by breaksrmine** [comment]
Works for me. Thank you!
